[package]
name = "post_processing"
version = "0.1.0"
edition = "2024"

[dependencies]
graphics = { path = "../graphics"}
specs = {path = "../specs"}
anymap = {path = "../anymap"}
rendering = {path = "../rendering"}
math = {path = "../math"}