[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "0.14.0"
glam = "0.29.2"
bitflags = "2.6.0"
image = "0.25.2"
pretty_env_logger = "0.5.0"
log = "0.4.22"
specs = {version = "0.20.0",default-features = false}
transform = {path = "../transform"}